services:
  postgres:
    image: postgres:15
    container_name: de5-postgres
    environment:
      POSTGRES_DB: bankingdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - de5_postgres_data:/var/lib/postgresql/data
      - ./sql/init_postgres.sql:/docker-entrypoint-initdb.d/init_postgres.sql

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: de5-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: de5-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: de5-zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  spark-master:
    image: spark:3.5.7-python3
    container_name: de5-spark-master
    hostname: spark-master
    depends_on:
      - kafka
      - postgres
    ports:
      - "7077:7077"
      - "8080:8080"
    volumes:
      - ./:/opt/project
    working_dir: /opt/project
    environment:
      HOME: /tmp
      SPARK_LOCAL_DIRS: /tmp/spark-local
    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.master.Master
      --host spark-master
      --port 7077
      --webui-port 8080

  spark-worker:
    image: spark:3.5.7-python3
    container_name: de5-spark-worker
    hostname: spark-worker
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    volumes:
      - ./:/opt/project
    working_dir: /opt/project
    environment:
      HOME: /tmp
      SPARK_LOCAL_DIRS: /tmp/spark-local
    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.worker.Worker
      spark://spark-master:7077
      --webui-port 8081
      --cores 4
      --memory 4G

  airflow-db:
    image: postgres:15
    container_name: airflow-db
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "55432:5432"
    volumes:
      - airflow_db_data:/var/lib/postgresql/data

  airflow-webserver:
    image: apache/airflow:2.8.0
    container_name: airflow-webserver
    depends_on:
      - airflow-db
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-db:5432/airflow
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      DOCKER_API_VERSION: "1.44"
    ports:
      - "8085:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - /var/run/docker.sock:/var/run/docker.sock
      - ./plugins:/opt/airflow/plugins
      - ./:/opt/project
    command: bash -c "pip install --no-cache-dir -r /opt/project/requirements.txt && airflow webserver"

  airflow-scheduler:
    image: apache/airflow:2.8.0
    container_name: airflow-scheduler
    depends_on:
      - airflow-webserver
      - airflow-db
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-db:5432/airflow
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      DOCKER_API_VERSION: "1.44"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - /var/run/docker.sock:/var/run/docker.sock
      - ./plugins:/opt/airflow/plugins
      - ./:/opt/project
    command: bash -c "pip install --no-cache-dir -r /opt/project/requirements.txt && airflow scheduler"

  marquez-db:
    image: postgres:14
    container_name: marquez-db
    environment:
      POSTGRES_USER: marquez
      POSTGRES_PASSWORD: marquez
      POSTGRES_DB: marquez
    ports:
      - "5433:5432"
    volumes:
      - marquez_db_data:/var/lib/postgresql/data

  marquez:
    image: marquezproject/marquez:0.50.0
    container_name: marquez
    depends_on:
      - marquez-db
    environment:
      POSTGRES_HOST: marquez-db
      POSTGRES_PORT: 5432
      POSTGRES_USER: marquez
      POSTGRES_PASSWORD: marquez
      POSTGRES_DB: marquez
    ports:
      - "5000:8080"
      - "5001:8081"

  marquez-web:
    image: marquezproject/marquez-web:0.50.0
    container_name: marquez-web
    depends_on:
      - marquez
    environment:
      MARQUEZ_HOST: marquez
      MARQUEZ_PORT: 5000
      WEB_PORT: 3000
      REACT_APP_ADVANCED_SEARCH: "false"
    ports:
      - "3000:3000"

volumes:
  de5_postgres_data:
  airflow_db_data:
  marquez_db_data: